### ISSUE TITLE
ze.clients.map(...).toSorted is not a function

### ISSUE THREAD

**Issue by aeoform** [99percentpeople/weblink#12]
TypeError: ze.clients.map(...).toSorted is not a function
    at Object.fn (https://webl.ink/assets/index-BGAR-qHo.js:14:1398)
    at FF (https://webl.ink/assets/index-jLEGppMH.js:2:5964)
    at Ln (https://webl.ink/assets/index-jLEGppMH.js:2:5891)
    at Object.Ku (https://webl.ink/assets/index-jLEGppMH.js:2:5101)
    at Object.get each [as each] (https://webl.ink/assets/index-BGAR-qHo.js:15:273)
    at https://webl.ink/assets/index-jLEGppMH.js:2:12687
    at Object.fn (https://webl.ink/assets/index-jLEGppMH.js:2:9000)
    at FF (https://webl.ink/assets/index-jLEGppMH.js:2:5964)
    at Ln (https://webl.ink/assets/index-jLEGppMH.js:2:5891)
    at N (https://webl.ink/assets/index-jLEGppMH.js:2:2217)
![微信截图_20241222164142](https://github.com/user-attachments/assets/490546ac-1919-44e2-83f2-9e99ee3489b5)

**Comment by 99percentpeople** [comment]
出现这个问题的原因是因为toSorted是一个比较新的API，你可以更新浏览器版本解决这个问题，有时间我也会修改使用兼容性更高的替代方式

**Comment by aeoform** [comment]
大概需要什么版本
华为浏览器
![微信截图_20241222165459](https://github.com/user-attachments/assets/f733cc30-83d1-4d78-bf88-fecec8179bd1)
Cheese Chrome
![微信截图_20241222165524](https://github.com/user-attachments/assets/9c021e98-ee45-4ce4-aff2-56ab7e24d9bb)

**Comment by 99percentpeople** [comment]
内核版本要110以上才行，如果你更新不了我也会很快解决这个问题

**Comment by aeoform** [comment]
好的，我更新一下
